# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 16:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_top_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='perchant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
